apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: humiocluster-internal-ingest 
  namespace: logging    
  labels:
    app.kubernetes.io/instance: humiocluster
    app.kubernetes.io/managed-by: terraform
    app.kubernetes.io/name: humio
    humio.com/node-pool: humiocluster-ingest-only
spec:
  dnsNames:
    - humiocluster-internal-ingest.logging
    - humiocluster-internal-ingest-headless.logging
  issuerRef:
    name: humiocluster
  secretName: humiocluster-internal-ingest