apiVersion: cert-manager.io/v1
kind: ClusterIssuer  
metadata:
  name: letsencrypt-cluster-issuer  
spec:
  acme:
    email: "dominic.bobak@gmail.com"
    privateKeySecretRef:
      name: letsencrypt-cluster-issuer-key  
    server: https://acme-v02.api.letsencrypt.org/directory  
    solvers:
      - http01:
          ingress:
            class: nginx