apiVersion: v1
kind: Service
metadata:
  name: humiocluster-nodeport-ui 
  namespace: logging            
spec:
  selector:
    humio.com/node-pool: humiocluster-ui-only 
  ports:
    - port: 8080
      targetPort: 8080
      name: logscale-port
  type: NodePort